rvm:
  - 2.2.3
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database workshops_test;' -U postgres
  - bundle exec rake db:drop db:create db:schema:load --trace
script:
  - RAILS_ENV=test bundle exec rspec
addons:
  postgresql: '9.3'
